### ISSUE TITLE
Error with the file "tor.py"

### ISSUE THREAD

**Issue by apektos1000** [Pure-L0G1C/YouTubeViews#20]
I run the example or other commands to run the script and I always get this:
Traceback (most recent call last):
  File "youtube.py", line 4, in <module>
    from core.tor import Tor
  File "C:\Users\Pro Gamer\Desktop\Youtube View Bots\YouTubeViews-master\core\tor.py", line 1, in <module>
    import socket, socks
ImportError: No module named socks

**Comment by asangaindunil** [comment]
me too

**Comment by vohrahul** [comment]
running
`pip install PySocks`

Should solve that error.
