### ISSUE TITLE
when i run the program i get this error how to resolve linux

### ISSUE THREAD

**Issue by hongyeecheah** [Pure-L0G1C/YouTubeViews#21]
Traceback (most recent call last):
  File "youtube.py", line 9, in <module>
    from core.browser import Browser
  File "/home/pi/Desktop/example/YouTubeViews/core/browser.py", line 3, in <module>
    import mechanize
ImportError: No module named mechanize

**Comment by zaogord** [comment]
install the modules listed in requirements.txt file.

**Comment by mohamadx2a2** [comment]
If python is dont work , try by python3 :/
