### ISSUE TITLE
ModuleNotFoundError: No module named 'mechanize'

### ISSUE THREAD

**Issue by Abdulsamipy** [Pure-L0G1C/YouTubeViews#45]
python youtube.py [120] [youtubeLinks.txt] [0:14] [0:21]
Traceback (most recent call last):
  File "youtube.py", line 10, in <module>
    from core.browser import Browser
  File "C:\...", line 2, in <module>
    import mechanize
ModuleNotFoundError: No module named 'mechanize'

mechanize is installed but still getting this error

**Comment by therealpj** [comment]
try this-
``` pip3 install mechanize ```

**Comment by Abdulsamipy** [comment]
> try this-
> `pip3 install mechanize`

when Im doing "pip3 install mechanized "
im getting requirements already satisfied 

but when im running the bot its giving me same error 

`ModuleNotFoundError: No module named 'mechanize'`

**Comment by magicketamine** [comment]
J'ai exactement le même problème rien ne fonctionne pour le résoudre peut être parsque je passe par termux sur Android je vais essayer par un Windows si le même problème persiste

**Comment by therealpj** [comment]
> when Im doing "pip3 install mechanized "

The module name is "mechanize", not "mechanized". Or was this a typo?

**Comment by Abdulsamipy** [comment]
Oh sorry that was a typo ...
