### ISSUE TITLE
ModuleNotFoundError: No module named 'socks'

### ISSUE THREAD

**Issue by KhalebOBrien** [Pure-L0G1C/YouTubeViews#52]
when I run `pip3 install core` I get this:
C:\Users\Peace\Desktop\you>pip3 install socks
Requirement already satisfied: socks in c:\users\peace\appdata\local\programs\python\python37-32\lib\site-packages (0)

But when I run `python youtube.py 300 urls.txt 38 65` It say:
C:\Users\Peace\Desktop\you>python youtube.py 100 urls.txt 38 65
Traceback (most recent call last):
  File "youtube.py", line 12, in <module>
    from core.tor import Tor
  File "C:\Users\Peace\Desktop\you\core\tor.py", line 1, in <module>
    import socks
ModuleNotFoundError: No module named 'socks'

I have installed socks, please what should I do?

**Comment by PvtSec** [comment]
It will not work on windows. Use a linux distro

**Comment by Sevada797** [comment]
<h1>pip install PySocks</h1>
