### ISSUE TITLE
ModuleNotFoundError: No module named 'mechanize'

### ISSUE THREAD

**Issue by anarchopingu** [Pure-L0G1C/YouTubeViews#61]
```
Traceback (most recent call last):
  File "youtube.py", line 10, in <module>
    from core.browser import Browser
  File "/home/pingu/Desktop/YouTubeViews/core/browser.py", line 2, in <module>
    import mechanize
ModuleNotFoundError: No module named 'mechanize'

```

**Comment by Shogun05** [comment]
https://pypi.org/project/mechanize/
just download the module from here.

**Comment by MaterialFuture** [comment]
Not sure if this ticket was solved as it's still marked as `open` but in case it hasn't then do as Shogun05 said, download the module and it should work. ie. running `pip install mechanize` solves this issue.

I'd highly recommend also updating the version of python on your machine to ensure you have pip installed using either the installer or (preferably) your system's package manager.
